### PR TITLE
Validations

### PR DESCRIPTION
**Pull request by shapiromatron**
Added a few additional validation checks:

- ensure file added is a text file
- we don't try to grab a 4th column in feature list, if a 4th column doesn't exist

### CODE REVIEW

**Comment by lavenderca** [comment]
Does the code [here](https://github.com/lavenderca/orio/blob/7ebb912b7b6c2c7113f38836bb4eb46d19091d51/orio/validators/feature_list.py#L50-L65) take care of the second commit?  We do allow three-column BED files, so I'm worried that the error message would be misleading.

**Comment by shapiromatron** [comment]
I loaded a random XML file I had on my computer, and I got an error here because a 4th column didn't exist:

https://github.com/lavenderca/orio/blob/master/orio/validators/feature_list.py#L67

You can remove the content on the second commit if that makes sense.

**Comment by lavenderca** [comment]
Sounds good to me.  Maybe just 'Feature name not found on line'?

**Comment by shapiromatron** [comment]
Removed the second commit; we'll just fix the xlsx file for now.

**Pull request merged**
